[package]
name = "zeno"
version = "0.1.0"
edition = "2024"


[profile.release]
debug = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
regex = "1.3.9"
rand = "0.9.1"
thousands = "0.2.0"
static_init = "1.0.4"
